server:
  port: 443
  ssl:
    key-store: 2386179_shop.junhesoft.com.cn.pfx
    key-store-password: 5Grg6ni4

spring:
    datasource:
        name: junhe
        #君和数据库
        url: jdbc:mysql://rm-uf689a9hgt79gmjo9oo.mysql.rds.aliyuncs.com:3306/junhe?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: junhe
        password: junheAdmin123!@#
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.junhe.demo.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql